apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-demo-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "gitops-demo-chart.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}
